config/urls.py
from user.views import RegisterView
from django.contrib import admin
from django.urls import path, include
import user
from config import settings
from django.conf.urls.static import static


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('los.urls', namespace='los')),
                  path('user/', include('user.urls', namespace='user')),

                  #
                  # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

                  path('api/', include('quizz_api.urls', namespace='quizz_api'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

los/urls.py
from django.urls import path
from . import views
from los.apps import LosConfig

app_name = LosConfig.name

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/<int:event_id>/attend/', views.event_attend, name='event_attend'),
    path('event/<int:user_id>/visit/', views.profile_attend, name='profile_attend'),
    path('articles', views.articles_list, name='articles_list'),
    path('user_events', views.all_user_events, name='all_user_events')
]

user/urls.py
from django.urls import path
from user.views import RegisterView
from user.apps import UserConfig
from django.contrib.auth.views import  LogoutView
from user.views import profile_view, CustomLoginView, RegisterView

app_name = UserConfig.name
urlpatterns = [

    # path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    # path('profile/', ProfileUpdateView.as_view(), name='profile'),
    # path('', RegisterView.as_view(), name='register')
    path('', RegisterView.as_view(template_name='user/registration.html'), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('login/', CustomLoginView.as_view(), name='login')
    # path('reset/', ResetView.as_view(), name='reset'),
    # path('reset/done/', ResetDoneView.as_view(), name='reset_done'),
    # path('reset/<uidb64>/<token>/', ResetConfirmView.as_view(), name='password_confirm'),
    # path('reset/compete/', ResetCompleteView.as_view(), name='confirm')]
]

los/models.py
from django.db import models

from user.models import User


# Create your models here.models

class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True)
    img = models.ImageField(upload_to='products/', verbose_name='изображение', null=True)
    attendees = models.ManyToManyField(User, related_name='events')

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    img = models.ImageField(upload_to='articles/', null=True)

    def __str__(self):
        return self.title

los/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from user.forms import ProfileForm, ImageUploadForm
from user.models import User
from .models import Event, Article


def all_user_events(request):
    users = User.objects.filter(events__isnull=False).distinct()
    print(users)
    return render(request, 'los/all_user_events.html', {'all_users': users})


def articles_list(request):
    articles = Article.objects.all()
    return render(request, 'los/articles_list.html', {'articles': articles})


def event_list(request):
    events = Event.objects.all()
    return render(request, 'los/events_list.html', {'events': events})


def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendees = event.attendees.all()
    return render(request, 'los/events_detail.html', {'event': event, 'attendees': attendees})


def event_attend(request, event_id):
    event = Event.objects.get(pk=event_id)
    event.attendees.add(request.user)
    return redirect(reverse('los:event_detail', args=[event_id]))


def profile_attend(request, user_id):
    user = User.objects.get(id=user_id)
    profile_form = ProfileForm(instance=user)
    image_form = ImageUploadForm(instance=user)

    return render(request, 'los/profile_link.html', {'current_user': user})

los/templates/los/all_user_events.html
{% extends 'los/base.html' %}
{% load mediapath %}
{% block content %}
<div class="container">
  <div class="row">
    {% for user in all_users %}
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <div class="user-avatar">
                <img src="{{ user.avatar|mediapath }}" class="rounded-circle img-thumbnail" alt="{{ user.email }}" style="width: 80px; height: 80px;">
              </div>
            </div>
            <div class="col-md-9">
              <h5 class="card-title">{{ user.first_name }}</h5>
              <p class="card-text">{{ user.email }}</p>
              <div class="events-list">
                {% for event in user.events.all %}
                <div class="event">
                  <div class="row">
                    <div class="col-md-12">
                      <h6>{{ event.title }}</h6>
                      <p>{{ event.description }}</p>
                      <a href="{% url 'los:event_detail' event.id %}" class="btn btn-primary btn-sm" style="background-color: #343a40;">Подробнее</a>
                    </div>
                  </div>
                  {% if not forloop.last %}
                  <hr> <!-- Добавляем линию разделения между мероприятиями -->
                  {% endif %}
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

los/templates/los/articles_list.html
{% extends 'los/base.html' %}
{% load mediapath %}
{% load cuttext %}
{% block title %}
    Полезные Статьи
{% endblock %}

{% block content %}
    <style>
        .card {
            border: 1px solid black; /* Устанавливаем черные рамки для карточек */
        }

        .card-body {
            text-align: center; /* Выравниваем текст внутри .card-body по центру */
        }
    </style>

    <div class="container mt-5">
        <div class="row">
            {% for article in articles %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ article.img|mediapath }}" class="card-img-top" alt="{{ event.title }}"
                             style="width:100%; height:auto; aspect-ratio:16/9;">
                        <div class="card-body">
                            <h5 class="card-title" style="font-family: Impact, sans-serif;">{{ article.title }}</h5>
                            <p class="card-text"
                               style="font-family: 'Playfair Display', serif; text-align: left;">{{ article.description|cut }}</p>
{#                            <a href="{% url 'los:event_detail' event_id=event.id %}" class="btn btn-primary"#}
{#                               style="background-color: #343a40;">Подробнее</a>#}
                            <a href="{{ article.link }}" class="btn btn-primary" target="_blank"
                               style="background-color: #343a40;">Перейти к статье</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

los/templates/los/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Моя Страница{% endblock %}</title>
    <!-- Подключаем Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .navbar {
            background-color: #343a40 !important; /* Цвет фона навигационной панели */
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="/">На главную</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    <!-- Добавляем кнопку Регистрации -->
                    <li class="nav-item">
                        <a class="nav-link btn text-white font-weight-bold" href="{% url 'los:all_user_events' %}">Куда
                            хотят сходить пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn text-white font-weight-bold" href="{% url 'los:articles_list' %}">Полезные
                            статьи</a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold"
                               href="{% url 'user:register' %}">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold" href="{% url 'user:login' %}">Войти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold"
                               href="{% url 'user:profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn text-white font-weight-bold" href="{% url 'user:login' %}">Выйти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Основное содержимое -->
<div class="container mt-5">
    {% block content %}
    {% endblock %}
</div>

<!-- Подключаем Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

los/templates/los/events_detail.html
{% extends 'los/base.html' %}
{% load static %}
{% load mediapath %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Добавляем ссылку на файл со стилями -->

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header" style="background-color: #343a40;">
                        <!-- Используем классы navbar-dark и bg-primary -->
                        <h2 style="color: white;">{{ event.title }}</h2> <!-- Изменяем цвет текста на белый -->
                    </div>
                    <div class="card-body">
                        <img src="{{ event.img|mediapath }}" class="card-img-top" alt="{{ event.title }}"
                             style="width:100%; height:auto; aspect-ratio:16/9;">
                        {#                        <img src="{{ event.img.url }}" alt="{{ event.title }}" class="img-fluid mb-3">#}
                        <p>{{ event.description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header" style="background-color: #343a40;">
                        <h2 style="color: white;">Участники</h2>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Фото</th>
                                <th>Имя участника</th>
                                <th>Профиль</th> <!-- Добавляем новый заголовок для ссылки на профиль -->
                            </tr>
                            </thead>
                            <tbody>
                            {% for attendee in attendees %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>
                                        {% if attendee.avatar %}
                                            <div class="avatar"
                                                 style="background-image: url('{{ attendee.avatar|mediapath }}')"></div>
                                        {% else %}
                                            <div class="avatar empty"></div>
                                        {% endif %}
                                    </td>
                                    <td>{{ attendee.email }}</td>
                                    <td> <!-- Добавляем новую ячейку для ссылки на профиль -->
                                        <a href="{% url 'los:profile_attend' attendee.id %}" class="btn btn-primary">Профиль</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-12">
                {% if user.is_authenticated %}
                    {% if user in event.attendees.all %}
                        <div class="alert alert-success" role="alert">
                            Вы успешно отметились, что идете на это мероприятие!
                        </div>
                    {% else %}
                        <form action="{% url 'los:event_attend' event.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Я иду!</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

los/templates/los/events_list.html
{% extends 'los/base.html' %}
{% load mediapath %}
{% load cuttext %}
{% block title %}
    Список мероприятий
{% endblock %}

{% block content %}
<style>
.card {
    border: 1px solid black; /* Устанавливаем черные рамки для карточек */
}

.card-body {
    text-align: center; /* Выравниваем текст внутри .card-body по центру */
}
</style>

<div class="container mt-5">
    <div class="row">
        {% for event in events %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ event.img|mediapath }}" class="card-img-top" alt="{{ event.title }}" style="width:100%; height:auto; aspect-ratio:16/9;">
                <div class="card-body">
                    <h5 class="card-title" style="font-family: Impact, sans-serif;">{{ event.title }}</h5>
                    <p class="card-text" style="font-family: 'Playfair Display', serif; text-align: left;">{{ event.description|cut }}</p>
                    <a href="{% url 'los:event_detail' event_id=event.id %}" class="btn btn-primary" style="background-color: #343a40;">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

los/templates/los/profile_link.html
{% extends 'los/base.html' %}
{% load static %}
{% load mediapath %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        {% if current_user.avatar %}
                            <div class="square">
                                <img src="{{ current_user.avatar|mediapath }}" class="img-fluid mb-3" alt="{{ user.username }}">
                            </div>
                        {% else %}
                            <div class="avatar empty"></div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" style="background-color: #343a40;">
                        <h2 style="color: white;">Профиль пользователя</h2>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Email:</th>
                                <td>{{ current_user.email }}</td>
                            </tr>
                            <tr>
                                <th>Имя:</th>
                                <td>{{ current_user.first_name }}</td>
                            </tr>
                            <tr>
                                <th>Фамилия:</th>
                                <td>{{ current_user.last_name }}</td>
                            </tr>
                            <tr>
                                <th>Ник в телеграм:</th>
                                <td>{{ current_user.tg_link }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}